apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mrplotter
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mrplotter
    spec:
      containers:
      - name: mrplotter
        image: btrdb/mrplotter:latest
        env:
          - name: ETCD_ENDPOINT
            value: http://etcd.sgs.svc.cluster.local:2379
          - name: BTRDB_ENDPOINTS
            value: http://btrdb-bootstrap.sgs.svc.cluster.local:4410
        ports:
        - containerPort: 443
          protocol: TCP
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mrplotter
  labels:
    app: mrplotter
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  selector:
    app: mrplotter
